# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3.9.1
      with:
        node-version:  16.13.2
    - name: Instalação do Mocha para teste
      run:
        cd src;
        npm install -g mocha;
        npm install
    - name: Execução do teste
      run: mocha src/test/convert.js

    - name: Construção da imagem Docker
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
      uses: docker/build-push-action@v6.16.0
      with:
        context: src
        file: src/Dockerfile
        push: true
        tags: gregoriofsg/conversao-temperatura:v1
          
        
    
